# Generated by Django 6.0.2 on 2026-02-27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0005_review"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="review",
            constraint=models.UniqueConstraint(
                fields=("product", "buyer"),
                name="unique_review_per_buyer_product",
            ),
        ),
    ]

