# Generated by Django 4.2.28 on 2026-02-28 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_conversation_message_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='is_automated',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddIndex(
            model_name='message',
            index=models.Index(fields=['is_automated'], name='users_messa_is_auto_1c4d7f_idx'),
        ),
    ]
